title: 苟利国家生死以，岂因祸福避趋之
author: Naico Wang
email: wanghy1984@gmail.com
description: Naico.Wang Working @ Farfetch
show_excerpts: true # set to true to show excerpts on the homepage
paginate: 10
paginate_path: "/:num/"

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Naico Wang
  tagline: Engineer
  location: Shanghai,China
  date_format: "%Y-%m-%d"
  sitemap: true # set to true to generate sitemap.xml content

  # generate social links in footer
  social_links:
    twitter: naicowanghy
    github:  naico
    linkedIn: naico

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.html

# Build settings
theme: plainwhite

plugins:
  - jekyll-paginate
