theme: jekyll-theme-modernist
title: Naico Wang
title_cn: 王宏宇(Naico)
description: SDE - PM - SH - China
description_cn: 软件开发工程师、软件项目经理 - 上海 - 中国
timezone: Asia/ShangHai
permalink: pretty
collections:
  posts:
    output: true