theme: jekyll-theme-modernist
title: Naico Wang
title_cn: 王宏宇(Naico)
description: Software Development Engineer - SH - China
description_cn: 软件开发工程师 - 上海 - 中国
timezone: Asia/ShangHai
permalink: pretty
collections:
  posts:
    output: true